//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeStore.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETHOADON
    {
        public int idHoaDon { get; set; }
        public int idDoUong { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual DOUONG DOUONG { get; set; }
        public virtual HOADON HOADON { get; set; }
    }
}
