//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeStore.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOUONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOUONG()
        {
            this.CHITIETHOADONs = new HashSet<CHITIETHOADON>();
            this.SUKIENs = new HashSet<SUKIEN>();
        }
    
        public int id { get; set; }
        public string MaDoUong { get; set; }
        public int MaLoaiDoUong { get; set; }
        public double GiaTien { get; set; }
        public string MoTa { get; set; }
        public string HinhAnh { get; set; }
        public int TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHOADON> CHITIETHOADONs { get; set; }
        public virtual LOAIDOUONG LOAIDOUONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUKIEN> SUKIENs { get; set; }
    }
}
