//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeStore.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADON()
        {
            this.CHITIETHOADONs = new HashSet<CHITIETHOADON>();
        }
    
        public int id { get; set; }
        public string MaHoaDon { get; set; }
        public Nullable<int> idKhachHang { get; set; }
        public Nullable<int> idNguoiDung { get; set; }
        public Nullable<int> idBan { get; set; }
        public Nullable<int> idTrangThai { get; set; }
        public Nullable<double> GiaGoc { get; set; }
        public Nullable<double> GiamGia { get; set; }
        public Nullable<double> TongCong { get; set; }
    
        public virtual BAN BAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHOADON> CHITIETHOADONs { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
        public virtual TRANGTHAIHOADON TRANGTHAIHOADON { get; set; }
    }
}
