//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_RULE
    {
        public int id { get; set; }
        public int MinimumAge { get; set; }
        public int MaximumAge { get; set; }
        public int Tax { get; set; }
        public int MinimumPrice { get; set; }
        public int MaximumPrice { get; set; }
    }
}
