//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMPORT_BILL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IMPORT_BILL()
        {
            this.IMPORT_BILL_DETAIL = new HashSet<IMPORT_BILL_DETAIL>();
        }
    
        public int id { get; set; }
        public string ImportID { get; set; }
        public string ImportName { get; set; }
        public System.DateTime ImportDate { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<double> Total { get; set; }
    
        public virtual C_USER C_USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMPORT_BILL_DETAIL> IMPORT_BILL_DETAIL { get; set; }
        public virtual SUPPLIER SUPPLIER { get; set; }
    }
}
