//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CFEntities : DbContext
    {
        public CFEntities()
            : base("name=CFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_RULE> C_RULE { get; set; }
        public virtual DbSet<C_SIZE> C_SIZE { get; set; }
        public virtual DbSet<C_TABLE> C_TABLE { get; set; }
        public virtual DbSet<C_USER> C_USER { get; set; }
        public virtual DbSet<AREA> AREAs { get; set; }
        public virtual DbSet<BILL> BILLs { get; set; }
        public virtual DbSet<BILL_DETAIL> BILL_DETAIL { get; set; }
        public virtual DbSet<CATEGORY> CATEGORies { get; set; }
        public virtual DbSet<DRINK> DRINKS { get; set; }
        public virtual DbSet<DRINKS_SIZE> DRINKS_SIZE { get; set; }
        public virtual DbSet<EVENT> EVENTs { get; set; }
        public virtual DbSet<GROUPUSER> GROUPUSERs { get; set; }
        public virtual DbSet<IMPORT_BILL> IMPORT_BILL { get; set; }
        public virtual DbSet<IMPORT_BILL_DETAIL> IMPORT_BILL_DETAIL { get; set; }
        public virtual DbSet<SERVICE> SERVICEs { get; set; }
        public virtual DbSet<SUPPLIER> SUPPLIERs { get; set; }
    }
}
