//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE100.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUGIAMGIA
    {
        public int id { get; set; }
        public string MaPhieuGiam { get; set; }
        public Nullable<int> idKhachHang { get; set; }
        public Nullable<double> GiaGiam { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
